### ISSUE TITLE
Can't make fatigue filter work with proxy entities

### ISSUE THREAD

**Issue by taiciat** [nixwiz/sensu-go-fatigue-check-filter#28]
Hi!

I'm having some problems to make the filter work. I'm using it in the typical cpu_check and also a custom check that simply make a curl to the local installed agent and create a proxy entity. When I enable the filter, none of the events with the fatigue annotations pass even when I run the curl more times than the defined occurrences.

I have run locally the [lib/fatigue_check.js](https://github.com/nixwiz/sensu-go-fatigue-check-filter/blob/master/lib/fatigue_check.js) and passed the event.json obtained using [the debug handler](https://blog.sensu.io/using-a-debug-handler-with-sensu-go) and noticed that it tries to find the annotations inside check.annotations but the annotations in the event.json are inside check.metadata.annotations.

Also the sensu documentation says that the annotations are at check.annotations, so I should be missing something. 
Aren't the event received by the filter and the event that is received by the handler the same (without any mutator)?

Any ideas why the filter never let pass the event even when the conditions are meet?
 
fatigue_asset.yml:
```
type: Asset
api_version: core/v2
metadata:
  name: sensu-go-fatigue-check-filter
  labels:
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/nixwiz/sensu-go-fatigue-check-filter
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/nixwiz/sensu-go-fatigue-check-filter
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 0.7.0
    io.sensu.bonsai.namespace: nixwiz
    io.sensu.bonsai.name: sensu-go-fatigue-check-filter
    io.sensu.bonsai.tags: eventfilter, filter
spec:
  builds:
  - url: https://assets.bonsai.sensu.io/fe1401d4e174d493dc2976e01140a70f94d6532c/sensu-go-fatigue-check-filter_0.7.0.tar.gz
    sha512: 1229e25b49e944ba0dc9534fa2150cf592e1dc31f2ad51c1dab60dadf1d989df82295f932364c5e2fc055015dc15c78ca0c643e8e1f1c3d1afb4e8a9aa51d38b
    filters: []
```

fatigue_filter.yml:
```
type: EventFilter
api_version: core/v2
metadata:
  name: fatigue_check
  namespace: default
spec:
  action: allow
  expressions:
  - fatigue_check(event)
  runtime_assets:
  - sensu-go-fatigue-check-filter
```

slack_handler.yml
```
type: Handler
api_version: core/v2
metadata:
  created_by: admin
  name: slack
  namespace: default
spec:
  command: sensu-slack-handler --channel '#xxxxxx'
  env_vars:
  - SLACK_WEBHOOK_URL=https://hooks.slack.com/services/xxxxxxxxxxxxxxxxxxxxxx
  filters:
  - is_incident
  - not_silenced
  - state_change_only
  - fatigue_check
  handlers: null
  runtime_assets:
  - sensu-slack-handler
  secrets: null
  timeout: 0
  type: pipe
```

cpu_check.yml
```
type: CheckConfig
api_version: core/v2
metadata:
  created_by: admin
  name: check_cpu
  namespace: default
  annotations:
    fatigue_check/occurrences: '3'
    fatigue_check/interval: '600'
    fatigue_check/allow_resolution: 'false'
spec:
  command: /etc/sensu/plugins/sensu-plugins-cpu-checks/bin/check-cpu.sh -w 90 -c 95
  handlers:
  - slack
  - email
  - asterisk
  - debug
  interval: 30
  publish: true
  subscriptions:
  - cpu
```

curl:
```
curl -X POST -H 'Content-Type: application/json' -d '{
    "check": {
        "metadata": {
            "name": "CHECKNAME",
            "labels": {
                "environment": "production"
            },
            "annotations": {
                "fatigue_check/occurrences": "2",
                "fatigue_check/interval": "3600",
                "fatigue_check/allow_resolution": "false"
            }
        },
        "handlers": [
            "slack",
            "email",
            "asterisk",
            "debug"
        ],
        "status": 2,
        "output": "critical test",
        "proxy_entity_name": "Test"
    }
}' http://127.0.0.1:3031/events
```
