### ISSUE TITLE
Filter blocks every message random logs 

### ISSUE THREAD

**Issue by chukynax** [nixwiz/sensu-go-fatigue-check-filter#4]
```
{"asset":"fatigue-check-filter","component":"asset-manager","level":"info","msg":"asset does not exist","time":"2019-09-19T20:04:43+03:00"}
```
```
{"component":"pipelined","error":"ReferenceError: 'fatigue_check' is not defined","level":"error","msg":"error executing JS","time":"2019-09-19T20:04:43+03:00"}
```
```
{"assets":["fatigue-check-filter"],"check_name":"check_disk_usage","check_namespace":"default","component":"pipelined","entity_name":"sensu","entity_namespace":"default","filter":"fatigue_check","level":"debug","msg":"denying event that does not match filter","time":"2019-09-19T20:04:43+03:00"}
```
```
{"check_name":"check_disk_usage","check_namespace":"default","component":"pipelined","entity_name":"sensu","entity_namespace":"default","filter":"fatigue_check","handler":"slack","level":"debug","msg":"denying event with custom filter","time":"2019-09-19T20:04:43+03:00"}
```
```
{"component":"pipelined","error":"ReferenceError: 'fatigue_check' is not defined","level":"error","msg":"error executing JS","time":"2019-09-19T20:04:43+03:00"}
```
```
{"assets":["fatigue-check-filter"],"check_name":"check_disk_usage","check_namespace":"default","component":"pipelined","entity_name":"sensu","entity_namespace":"default","filter":"fatigue_check","level":"debug","msg":"denying event that does not match filter","time":"2019-09-19T20:04:43+03:00"}
```
```
{"check_name":"check_disk_usage","check_namespace":"default","component":"pipelined","entity_name":"sensu","entity_namespace":"default","handler":"alerta","level":"info","msg":"event filtered","time":"2019-09-19T20:04:43+03:00"}
```
everything was set up according to examples

**Comment by nixwiz** [comment]
Hi @chukynax, can you post your exact entries for the asset, filter, and handler?

**Comment by chukynax** [comment]
```
---
type: Asset
api_version: core/v2
metadata:
  name: sensu-go-fatigue-check-filter_any_noarch
  labels: 
  annotations:
    io.sensu.bonsai.url: https://bonsai.sensu.io/assets/nixwiz/sensu-go-fatigue-check-filter
    io.sensu.bonsai.api_url: https://bonsai.sensu.io/api/v1/assets/nixwiz/sensu-go-fatigue-check-filter
    io.sensu.bonsai.tier: Community
    io.sensu.bonsai.version: 0.2.1
    io.sensu.bonsai.namespace: nixwiz
    io.sensu.bonsai.name: sensu-go-fatigue-check-filter
    io.sensu.bonsai.tags: eventfilter
spec:
  url: https://assets.bonsai.sensu.io/82dc07cb79697eb041f731f9de748c4320aec07a/sensu-go-fatigue-check-filter_0.2.1.tar.gz
  sha512: 7fd5343fc1feee9277d012221df90412ab5e30287e8bf9b0fd94475f59997baec96b37412522fe3291f1fba64dd3cb9c1ffe3248a261ea72b984342a88bae10c
  filters: []
```
